# Generated by Django 5.0.7 on 2024-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='здесь вы можете написать локацию', max_length=100, verbose_name='локация')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='дата создается автоматически', verbose_name='дата')),
                ('category', models.CharField(help_text='здесь вы можете написать категорию', max_length=50, verbose_name='категория')),
                ('text', models.TextField(help_text='здесь вы можете написать свой текст', verbose_name='текст')),
            ],
        ),
    ]
