# Generated by Django 5.0.7 on 2024-07-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Здесь будет название вашей группы', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(help_text='Здесь будет уникальный адресс', unique=True, verbose_name='Уникальный адресс')),
                ('description', models.TextField(help_text='Здесь будет описание', verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='groups',
            field=models.ForeignKey(blank=True, help_text='Здесь будут ваши группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.groups', verbose_name='Группы'),
        ),
    ]
